# config

# dataset path - UPDATED TO CORRECT DATA LOCATION
data_root: /net/milz/datasets/Physics_Informed_CNN/heat_layout_data/200x200_0.045_0.055/simple_component/FDM/
train_list: /net/milz/datasets/Physics_Informed_CNN/heat_layout_data/train.txt
val_list: /net/milz/datasets/Physics_Informed_CNN/heat_layout_data/val.txt
test_list: /net/milz/datasets/Physics_Informed_CNN/heat_layout_data/test.txt
#data_root: /mnt/jfs/zhaoxiaoyu/data/ul/simple_component/FDM
train_dir: train
val_dir: train
test_dir: train


resume_from_checkpoint: null


# dataset properties
load_name: F # F, list
length: 0.1
nx: 200 # select from [50, 100, 150, 200, 400, 800]


# additive Gaussian noise
noise_std: 0.0003 # Standard deviation of Gaussian noise to add to input (set to 0.0 for no noise)
#Low-frequency noises Gaussian blur
blur_kernel_size: 0 #following the recommended conventional rule
blur_sigma: 0

u_D: 298
seed: 34 #test for 10 to 20 for different seeds for averaging results
bcs:
#  - [[0, 0.15],[0, 0.25]]
#  - [[0.0400, 0.0], [0.0600, 0.0]]
#  - [[0.0495, 0.0], [0.0505, 0.0]]
  - [[0.0450, 0.0], [0.0550, 0.0]]
#  - [[]]

batch_size: 1  # Increased for better GPU utilization
max_epochs: 30  # More meaningful training for batch jobs
lr: 0.001

# GPU configuration for SLURM - use 1 GPU (will map to GPU ID 0)
gpus: 1
use_16bit: false  # for speedup true 
val_check_interval: 1.0
# num_workers in dataloader - set to 1 to avoid warnings  
num_workers: 4

# preprocessing of data
# input
mean_layout: 0
std_layout: 10000
# output
# mean_heat: 0
# std_heat: 1

